### ISSUE TITLE
Where locate log file in docker container

### ISSUE THREAD

**Issue by zzwxrchi** [nvllsvm/linode-dynamic-dns#7]
Where can I locate log file in docker container ?

Is still function in May 2021 with api linode ?

And linode tocken permissions to create ?  
Access	         None	        Read Only	       Read/Write
Account  
Domains
Events
Images
IPs
Kubernetes
Linodes
Longview
NodeBalancers
Object Storage
StackScripts
Volumes

Thanks !!

**Comment by zzwxrchi** [comment]
I get.

########### In linode panel #########
1.  Create dominio or subDominio to manage his dynamic ip in https://cloud.linode.com/dashboard
           Example: drive.xxxxxx.com

2.  In MY PROFILE -> API Tokens -> Creat a Psersonal Acccess Token
			Label: Label Name
			Expiry: Never
			permissions -> only Domains: Read/Write
			Create Token -> copy token string

########### In local server pc #######
3. Create: docker-compose file:
         vim docker-compose.yml
		# file created with docker cmd in https://www.composerize.com/
		version: '3.3'
		services:
			linode-dynamic-dns:
				environment:
					- DOMAIN=xxxxxx.com
					- HOST=drive
					- TOKEN=token string
					- FREQUENCY=1440  #daily
				image: nvllsvm/linode-dynamic-dns
        		        restart: always

4. execute:  sudo docker-compose up -d

5.  checked
	curl ipinfo.io/ip # get dinamic public ip in excute pc

	ping -c3 xxxxxx.com   # check public ip of domain

	ping -c3 drive.xxxxxx.com  # check public ip of subDomain drive

**Comment by andrewrabert** [comment]
The container logs to stdout. It is also still functional in 2024.

**Comment by zzwxrchi** [comment]
> The container logs to stdout. It is also still functional in 2024.

Yes !! It's great !!

I did same change at linode_dynamic_dns.py file in my [fork](https://github.com/zzwxrchi/linode-dynamic-dns)
And now we can use naked domain and a list of sub domains (see the note_systemd_instalar file)


Thanks a lot !
