### ISSUE TITLE
Possible to update base A record?

### ISSUE THREAD

**Issue by shanelord01** [nvllsvm/linode-dynamic-dns#8]
Hi,

Just looking for the ability to update the base domain A record.

ie instead of updating "ddns.mydomain.com", I'd like to update "mydomain.com"

Is this possible? I can do this on Cloudflare and Google Domains, hoping to do it on Linode.

Thanks.

**Comment by andrewrabert** [comment]
This is now possible by leaving the hostname (`--dns-hostname` or `LINODE_DNS_HOSTNAME`) unset or empty.
